package com.outlay.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.outlay.dao.Category;
import com.outlay.dao.Expense;

import com.outlay.dao.CategoryDao;
import com.outlay.dao.ExpenseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoryDaoConfig;
    private final DaoConfig expenseDaoConfig;

    private final CategoryDao categoryDao;
    private final ExpenseDao expenseDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        expenseDaoConfig = daoConfigMap.get(ExpenseDao.class).clone();
        expenseDaoConfig.initIdentityScope(type);

        categoryDao = new CategoryDao(categoryDaoConfig, this);
        expenseDao = new ExpenseDao(expenseDaoConfig, this);

        registerDao(Category.class, categoryDao);
        registerDao(Expense.class, expenseDao);
    }
    
    public void clear() {
        categoryDaoConfig.getIdentityScope().clear();
        expenseDaoConfig.getIdentityScope().clear();
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public ExpenseDao getExpenseDao() {
        return expenseDao;
    }

}
